lib/fmzn_web/router.ex
defmodule FmznWeb.Router do
  use FmznWeb, :router

  alias FmznWeb.ShoppingCart


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ShoppingCart

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FmznWeb do
    pipe_through :browser

    resources "/reviews", ReviewController


    get "/", PageController, :index
    get "/first", PageController, :first
    get "/products", ProductController, :index
    get "/products/new", ProductController, :new
    post "/products", ProductController, :create
    get "/products/:id", ProductController, :show
    get "/privacy", PageController, :privacy
    get "/load", PageController, :load_products
    post "/products/addtobasket/:product_id", ProductController, :add_to_basket
    get "/basket", PageController, :basket
    get "/category/:category", PageController, :category
  end

  # Other scopes may use custom stacks.
   scope "/api", FmznWeb do
     pipe_through :api
     get "/products", ProductController, :products_json
     get "/random", ProductController, :get_product
   end
end

lib/fmzn/resources/product.ex
defmodule Fmzn.Resources.Product do
  use Ecto.Schema
  import Ecto.Changeset

  alias Fmzn.Resources.ProductPoints
  alias Fmzn.Resources.Review

  @derive {Jason.Encoder, only: [:title, :description, :img, :primary_category, :secondary_category, :productpoints]}

  schema "products" do
    field :description, :string
    field :discount, :float
    field :img, :string
    field :price, :float
    field :title, :string
    field :primary_category, :string
    field :secondary_category, :string
    field :slug, :string
    field :visible, :boolean

    has_many :productpoints, ProductPoints, on_delete: :delete_all
    has_many :reviews, Review, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(product, attrs) do
    product
    |> cast(attrs, [:title, :img, :description, :price, :discount, :primary_category, :secondary_category, :slug])
    |> unique_constraint(:slug)
    |> cast_assoc(:productpoints, required: true)
    |> cast_assoc(:reviews, required: false)
    |> validate_required([:title, :description, :price, :discount, :slug])
  end

end

lib/fmzn_web/controllers/product_controller.ex
defmodule FmznWeb.ProductController do
  use FmznWeb, :controller

  alias Fmzn.Resources
  alias Fmzn.Resources.Product
  alias Fmzn.Resources.ProductPoints
  alias Fmzn.Resources.Review

  def index(conn, _params) do
    products = Resources.list_products()
    render(conn, "index.html", products: products)
  end

  def new(conn, _params) do
    changeset = Resources.change_product(%Product{productpoints: [%ProductPoints{}, %ProductPoints{}, %ProductPoints{}]})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => product_params}) do
    product_params = Map.put(product_params, "slug", product_params["title"] |> String.downcase |> String.replace(" ", "-"))
    product_params = Map.put(product_params, "discount", Enum.random([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

    case Resources.create_product(product_params) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        IO.inspect(changeset)
        render(conn, "new.html", changeset: changeset)
    end
  end


  def show(conn, %{"id" => id}) do
    product = Resources.get_product_by_slug!(id)
    review = %Review{product_id: product.id}
    changeset = Resources.change_review(review)

    random_products = Resources.find_random_products_excluding_this_one(id)

    advert = Resources.get_advert(1)

    render(conn, "show.html", product: product, changeset: changeset, token: get_csrf_token(), advert: advert, random_products: random_products)
  end

  def add_to_basket(conn, %{"product_id" => pid}) do
    product = Resources.get_product_by_slug!(pid)
    b = get_session(conn, :basket)
    shopping_basket = case b do
      nil -> [pid]
      _ -> b ++ [pid]
    end
    put_session(conn, :basket, shopping_basket)
    |> put_flash(:info, "Added to shopping cart successfully.")
    |> redirect(to: Routes.product_path(conn, :show, product.slug))

  end

  def products_json(conn, _params) do
    json(conn, Jason.encode!(Resources.list_products()))
  end

  def get_product(conn, _params) do
    product = Resources.get_random_product()
    json(conn, %{title: product.title, img: product.img, description: product.description, url: "https://fmzn.shop/products/#{product.slug}"})
  end

end

lib/fmzn_web/views/product_view.ex
defmodule FmznWeb.ProductView do
  use FmznWeb, :view

  def make_sku do
    "#{get_random_letters(2)}#{Enum.random(300..1000)}-#{get_random_letters(2)}#{Enum.random(1000..10000)}-#{get_random_letters(2)}"
  end

  def max_description_length(description) do
    String.slice(description, 0..150)
  end

  def get_random_letters(n) do
    Enum.map(1..n, fn(_) -> Enum.random(["A","B","C", "D","E","F","G","H","J","K","L","M","N","P","Q","R","S","T"]) end) |> List.to_string
  end

  def currency_format(val) do
    Float.floor(val, 2)
  end

  def image_path(conn, product) do
    if (product.img) do
      product.img
    else
      Routes.static_path(conn, "/images/placeholder.png")
    end
  end

end

lib/fmzn_web/templates/product/advert.html.eex
<div class="advert" style="background-image: url('/images/placeholder.png')">
    <%= @advert.txt %>
</div>

lib/fmzn_web/templates/product/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<div class="form-group">
  <%= label f, :title %>
  <%= text_input f, :title, class: "form-control" %>
  <%= error_tag f, :title %>

  <%= label f, "Image URL" %>
  <%= text_input f, :img, class: "form-control" %>
  <%= error_tag f, :img %>

  <%= label f, :description %>
  <%= text_input f, :description, class: "form-control" %>
  <%= error_tag f, :description %>

  <%= label f, "Price £" %>
  <%= number_input f, :price, step: "any", class: "form-control" %>
  <%= error_tag f, :price %>

   <%= label f, :primary_category %>
    <%= select f, :primary_category, Fmzn.Categories.options, class: "form-control" %>
    <%= error_tag f, :primary_category %>

    <%= label f, :secondary_category %>
    <%= text_input f, :secondary_category, class: "form-control" %>
    <%= error_tag f, :secondary_category %>

    <h2>Marketing points</h2>
   <%= inputs_for f, :productpoints, fn p -> %>
      <div class="form-group">
        <%= label p, "Text", class: "control-label" %>
        <%= text_input p, :txt, class: "form-control" %>
        <%= error_tag p, :txt %>
      </div>
    <% end %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

</div>

lib/fmzn_web/templates/product/new.html.eex
<h1>New Product</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.product_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.review_path(@conn, :index) %></span>

lib/fmzn_web/templates/product/review.html.eex
<h1>Leave a review</h1>
<%= form_for @changeset, @action, fn f -> %>
<div class="form-group">
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :score %>
  <%= select f, :score, 10..1, class: "form-control" %>
  <%= error_tag f, :score %>

  <%= label f, :description %>
  <%= text_input f, :description, class: "form-control" %>
  <%= error_tag f, :description %>

   <%= hidden_input f, :product_id %>
   <%= hidden_input f, :product_slug, value: @product.slug %>
    <br />
   <%= submit "Save", class: "btn btn-primary btn-large float-right" %>

  </div>
<% end %>

lib/fmzn_web/templates/product/share.html.eex
<div class="share">
    <div class="addthis_inline_share_toolbox"></div>
</div>

lib/fmzn_web/templates/product/show.html.eex
<div class="row">
    <div class="col">
        <h1><%= @product.title %> <span class="badge badge-secondary">New</span></h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-4 col-xs-12">
        <img class="rounded float-left img-fluid" src="<%= image_path(@conn, @product) %>">

    </div>
    <div class="col-sm-8 col-xs-12">
        <div class="row">
            <div class="col product-details">
                <div><a href="<%= Routes.page_path(@conn, :category, @product.primary_category) %>"><%= @product.primary_category %></a> <i class="fa fa-arrow-circle-right"></i> <a href="#"><%= @product.secondary_category %></a></div>
                <div class="price"><del>£<%= currency_format(@product.price) %></del> £<%= currency_format(@product.price * @product.discount) %></div>
                <div>SKU: <%= make_sku() %></div>
                <div class="availibility">Availibility: <%= Enum.random(1..100) %> in stock</div>
                <div><%= @product.description %></div>
                <br />
                <div>
                    <ul class="list-group list-group-flush">
                        <%= for point <- @product.productpoints do %>
                            <li class="list-group-item"><%= point.txt %></li>
                        <% end %>
                    </ul>
                </div>
                <br />
                <a href="/first" class="btn btn-primary btn-lg btn-block">Buy Now + Fmzn First</a>
                <a href="/first" class="btn btn-primary btn-lg btn-block">Subscribe to Fmzn First</a>
                <br><br>
            <form action="/products/addtobasket/<%= @product.slug %>" method="post">
                <input type="hidden" value="<%= @token %>" name="_csrf_token"/>
                    <%= submit "Buy Now", class: "btn btn-secondary btn-block" %>
             </form>
             <br />
            <button class="btn btn-secondary btn-block" onclick="alert('It looks like your current credit score <%= Enum.random([0.9, 1534, 0.001]) %> is not enough.  This check does effect your credit score!')">Buy with InstaCredit <sub>TM</sub></button>
            <%= render "share.html" %>
        </div>
      </div>
    </div>
</div>
<br />
<div class="row justify-content-end">
    <div class="col-sm-8 col-xs-12">
        <h4>People like you also like: </h4>
        <%= render FmznWeb.PageView, "products.html", products: @random_products, category: "", conn: @conn %>
    </div>
</div>
<br />
<div class="row justify-content-end">
    <div class="col-sm-8 col-xs-12">
        <h1><%= length(@product.reviews) %> Reviews</h1>
        <div class="row">
           <%= for review <- @product.reviews do %>
              <div class="col">
                <div class="card">
                     <div class="card-body">
                            <%= review.score %> / 10 <br> <%= review.description %>
                      </div>
                </div>
              </div>
          <% end %>
         </div>
        <%= render "review.html", Map.put(assigns, :action, Routes.review_path(@conn, :create)) %>
    </div>
</div>

</div>