lib/fmzn_web/router.ex
defmodule FmznWeb.Router do
  use FmznWeb, :router

  alias FmznWeb.ShoppingCart


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ShoppingCart

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FmznWeb do
    pipe_through :browser

    resources "/reviews", ReviewController


    get "/", PageController, :index
    get "/first", PageController, :first
    get "/products", ProductController, :index
    get "/products/new", ProductController, :new
    post "/products", ProductController, :create
    get "/products/:id", ProductController, :show
    get "/privacy", PageController, :privacy
    get "/load", PageController, :load_products
    post "/products/addtobasket/:product_id", ProductController, :add_to_basket
    get "/basket", PageController, :basket
    get "/category/:category", PageController, :category
  end

  # Other scopes may use custom stacks.
   scope "/api", FmznWeb do
     pipe_through :api
     get "/products", ProductController, :products_json
     get "/random", ProductController, :get_product
   end
end

lib/fmzn_web/templates/page/basket.html.eex
<h1>My Basket</h1>
<%= for product <- @products do %>
    <%= render "product_preview.html", conn: @conn, product: product %>
<% end %>

<button class="btn btn-primary btn-lg float-right" onclick="window.confirm('Are you sure?');">Buy all immediately</button>

lib/fmzn_web/templates/page/first.html.eex
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5" style="z-index: 1;">
        <h1 class="display-4 font-weight-normal">Fmzn First</h1>
        <p class="lead font-weight-normal">Offers offers offers</p>
        <a class="btn btn-outline-secondary" href="#">Coming soon</a>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
            <h2 class="display-5">Movies</h2>
            <p class="lead">A range over over 10 million movies, continuously watch for 160 years.</p>
        </div>
        <div class="bg-dark box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-primary mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <div class="my-3 p-3">
            <h2 class="display-5">Games</h2>
            <p class="lead">Get to the points! Fun for friends and family. </p>
        </div>
        <div class="bg-dark box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 p-3">
            <h2 class="display-5">Musak</h2>
            <p class="lead">Hearing is everything</p>
        </div>
        <div class="bg-primary box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
            <h2 class="display-5">Books</h2>
            <p class="lead">We also have them.</p>
        </div>
        <div class="bg-light box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
</div>


<style>
    .container {
  max-width: 960px;
}

/*
 * Custom translucent site header
 */

.site-header {
  background-color: rgba(0, 0, 0, .85);
  -webkit-backdrop-filter: saturate(180%) blur(20px);
  backdrop-filter: saturate(180%) blur(20px);
}
.site-header a {
  color: #999;
  transition: ease-in-out color .15s;
}
.site-header a:hover {
  color: #fff;
  text-decoration: none;
}

/*
 * Dummy devices (replace them with your own or something else entirely!)
 */

.product-device {
  position: absolute;
  right: 10%;
  bottom: -30%;
  width: 300px;
  height: 540px;
  background-color: #333;
  border-radius: 21px;
  -webkit-transform: rotate(30deg);
  transform: rotate(30deg);
}

.product-device::before {
  position: absolute;
  top: 10%;
  right: 10px;
  bottom: 10%;
  left: 10px;
  content: "";
  background-color: rgba(255, 255, 255, .1);
  border-radius: 5px;
}

.product-device-2 {
  top: -25%;
  right: auto;
  bottom: 0;
  left: 5%;
  background-color: #e5e5e5;
}


/*
 * Extra utilities
 */

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

.flex-equal > * {
  -ms-flex: 1;
  -webkit-box-flex: 1;
  flex: 1;
}
@media (min-width: 768px) {
  .flex-md-equal > * {
    -ms-flex: 1;
    -webkit-box-flex: 1;
    flex: 1;
  }
}

.overflow-hidden { overflow: hidden; }
</style>

lib/fmzn_web/templates/page/insert.html.eex
<h1><%= @prods %> product(s) inserted</h1>

lib/fmzn_web/templates/page/privacy.html.eex
<h1>Privacy Settings</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <%= render "privacy_forms/personal.html" %>
        </div>
        <div class="col-md-6 col-sm-12">
            <%= render "privacy_forms/location.html" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <%= render "privacy_forms/sharing.html" %>
        </div>
        <div class="col-md-6 col-sm-12">
            <%= render "privacy_forms/contact.html" %>
        </div>
    </div>

    <button class="btn btn-primary btn-large float-right" onclick="alert('Sorry, settings could not be changed')">
        Update
    </button>
</div>

lib/fmzn_web/templates/page/product_preview.html.eex
    <div class="container-fluid product-preview">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <img class="rounded float-left img-fluid preview" src="<%= image_path(@conn, @product) %>">
            </div>
            <div class="col-sm-10 col-xs-12">
                <h1><%= @product.title %></h1>
                <h3 class="price">£<%= currency_format(@product.price * @product.discount) %></h3>
                 <%= render "rating.html", rating: Enum.random([1,2,3,4,5]) %>
                <p><%= @product.description %></p>
            </div>
        </div>
    </div>

lib/fmzn_web/templates/page/products.html.eex
<h1><%= @category %></h1>
<div class="row">
    <%= for product <- @products do %>
    <a href="<%= Routes.product_path(@conn, :show, product.slug) %>">
            <div class="col-sm-4">
                <div class="card h-100">
                    <div class="card-body">
                        <img class="rounded mx-auto d-block img-fluid preview" src="<%= image_path(@conn, product) %>">
                        <h5 class="card-title"><%= product.title %></h5></a>
                        <h5 class="price"><sup>£</sup><%= currency_format_pounds(product.price * product.discount) %><sup><%= Enum.random(["99", "04", "55"])%></sup></h5>
                        <h5 class="price-strikethrough">£<%= currency_format(product.price) %></h5>
                        <%= render "rating.html", rating: Enum.random([1,2,3,4,5]) %>
                    </div>
                </div>
            </div>
        </a>
    <% end %>
</div>

lib/fmzn_web/templates/page/rating.html.eex
<div class="ratings-container">
<%= for i <- 1..5 do %>
    <%= if(i <= @rating) do %>
        <div class="clip-star"></div>
        <% else %>
        <div class="clip-star-empty"></div>
        <% end %>

<% end %>
    <span class="small-text"><%= Enum.random(1..1000) %></span>
</div>